services:
    postgres:
        env_file: .env
        container_name: postgres_db_${DB_NAME}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

    app:
        env_file: .env
        environment:
            DATABASE_URL: ${DATABASE_URL}
        build: .
        container_name: nextjs_app
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - postgres

volumes:
    postgres_data:
